name: Recipes Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run tests
        run: npm test
        working-directory: ./backend

      - name: Deploy no Render
        if: github.ref == 'refs/heads/master'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
